#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemaGYMFITNESS.Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="proyecto")]
	public partial class bdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Insertcliente_venta_produc(cliente_venta_produc instance);
    partial void Updatecliente_venta_produc(cliente_venta_produc instance);
    partial void Deletecliente_venta_produc(cliente_venta_produc instance);
    partial void Insertclientes(clientes instance);
    partial void Updateclientes(clientes instance);
    partial void Deleteclientes(clientes instance);
    partial void Insertcompra_producto(compra_producto instance);
    partial void Updatecompra_producto(compra_producto instance);
    partial void Deletecompra_producto(compra_producto instance);
    partial void Insertdetalle_compra_producto(detalle_compra_producto instance);
    partial void Updatedetalle_compra_producto(detalle_compra_producto instance);
    partial void Deletedetalle_compra_producto(detalle_compra_producto instance);
    partial void Insertdetalle_venta_producto(detalle_venta_producto instance);
    partial void Updatedetalle_venta_producto(detalle_venta_producto instance);
    partial void Deletedetalle_venta_producto(detalle_venta_producto instance);
    partial void InsertEmpleados(Empleados instance);
    partial void UpdateEmpleados(Empleados instance);
    partial void DeleteEmpleados(Empleados instance);
    partial void Insertfaltas_Empleados(faltas_Empleados instance);
    partial void Updatefaltas_Empleados(faltas_Empleados instance);
    partial void Deletefaltas_Empleados(faltas_Empleados instance);
    partial void Insertmembresia_clientes(membresia_clientes instance);
    partial void Updatemembresia_clientes(membresia_clientes instance);
    partial void Deletemembresia_clientes(membresia_clientes instance);
    partial void Insertpago_sueldo_Empleados(pago_sueldo_Empleados instance);
    partial void Updatepago_sueldo_Empleados(pago_sueldo_Empleados instance);
    partial void Deletepago_sueldo_Empleados(pago_sueldo_Empleados instance);
    partial void Insertproducto(producto instance);
    partial void Updateproducto(producto instance);
    partial void Deleteproducto(producto instance);
    partial void Insertproveedores(proveedores instance);
    partial void Updateproveedores(proveedores instance);
    partial void Deleteproveedores(proveedores instance);
    partial void Insertventa_producto(venta_producto instance);
    partial void Updateventa_producto(venta_producto instance);
    partial void Deleteventa_producto(venta_producto instance);
    #endregion
		
		public bdDataContext() : 
				base(global::systemaGYMFITNESS.Properties.Settings.Default.proyectoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asistencia_Clientes> Asistencia_Clientes
		{
			get
			{
				return this.GetTable<Asistencia_Clientes>();
			}
		}
		
		public System.Data.Linq.Table<categoria> categoria
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<cliente_venta_produc> cliente_venta_produc
		{
			get
			{
				return this.GetTable<cliente_venta_produc>();
			}
		}
		
		public System.Data.Linq.Table<clientes> clientes
		{
			get
			{
				return this.GetTable<clientes>();
			}
		}
		
		public System.Data.Linq.Table<compra_producto> compra_producto
		{
			get
			{
				return this.GetTable<compra_producto>();
			}
		}
		
		public System.Data.Linq.Table<detalle_compra_producto> detalle_compra_producto
		{
			get
			{
				return this.GetTable<detalle_compra_producto>();
			}
		}
		
		public System.Data.Linq.Table<detalle_venta_producto> detalle_venta_producto
		{
			get
			{
				return this.GetTable<detalle_venta_producto>();
			}
		}
		
		public System.Data.Linq.Table<Empleados> Empleados
		{
			get
			{
				return this.GetTable<Empleados>();
			}
		}
		
		public System.Data.Linq.Table<faltas_Empleados> faltas_Empleados
		{
			get
			{
				return this.GetTable<faltas_Empleados>();
			}
		}
		
		public System.Data.Linq.Table<membresia_clientes> membresia_clientes
		{
			get
			{
				return this.GetTable<membresia_clientes>();
			}
		}
		
		public System.Data.Linq.Table<pago_sueldo_Empleados> pago_sueldo_Empleados
		{
			get
			{
				return this.GetTable<pago_sueldo_Empleados>();
			}
		}
		
		public System.Data.Linq.Table<pagos_cliente> pagos_cliente
		{
			get
			{
				return this.GetTable<pagos_cliente>();
			}
		}
		
		public System.Data.Linq.Table<producto> producto
		{
			get
			{
				return this.GetTable<producto>();
			}
		}
		
		public System.Data.Linq.Table<proveedores> proveedores
		{
			get
			{
				return this.GetTable<proveedores>();
			}
		}
		
		public System.Data.Linq.Table<venta_producto> venta_producto
		{
			get
			{
				return this.GetTable<venta_producto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asistencia_Clientes")]
	public partial class Asistencia_Clientes
	{
		
		private string _cedula_cliente;
		
		private System.Nullable<System.DateTime> _fecha;
		
		public Asistencia_Clientes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="VarChar(50)")]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					this._cedula_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_categoria;
		
		private string _nombre_categoria;
		
		private EntitySet<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(string value);
    partial void Onid_categoriaChanged();
    partial void Onnombre_categoriaChanging(string value);
    partial void Onnombre_categoriaChanged();
    #endregion
		
		public categoria()
		{
			this._producto = new EntitySet<producto>(new Action<producto>(this.attach_producto), new Action<producto>(this.detach_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_categoria", DbType="VarChar(50)")]
		public string nombre_categoria
		{
			get
			{
				return this._nombre_categoria;
			}
			set
			{
				if ((this._nombre_categoria != value))
				{
					this.Onnombre_categoriaChanging(value);
					this.SendPropertyChanging();
					this._nombre_categoria = value;
					this.SendPropertyChanged("nombre_categoria");
					this.Onnombre_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_producto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<producto> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente_venta_produc")]
	public partial class cliente_venta_produc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cedula_cliente;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _direccion;
		
		private string _telefono;
		
		private EntitySet<venta_producto> _venta_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncedula_clienteChanging(string value);
    partial void Oncedula_clienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    #endregion
		
		public cliente_venta_produc()
		{
			this._venta_producto = new EntitySet<venta_producto>(new Action<venta_producto>(this.attach_venta_producto), new Action<venta_producto>(this.detach_venta_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					this.Oncedula_clienteChanging(value);
					this.SendPropertyChanging();
					this._cedula_cliente = value;
					this.SendPropertyChanged("cedula_cliente");
					this.Oncedula_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venta_produc_venta_producto", Storage="_venta_producto", ThisKey="cedula_cliente", OtherKey="cedula_cliente")]
		public EntitySet<venta_producto> venta_producto
		{
			get
			{
				return this._venta_producto;
			}
			set
			{
				this._venta_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_venta_producto(venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.cliente_venta_produc = this;
		}
		
		private void detach_venta_producto(venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.cliente_venta_produc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cedula;
		
		private string _nombres;
		
		private string _apellidos;
		
		private string _direccion;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private string _telefono;
		
		private string _celular;
		
		private System.Nullable<decimal> _peso;
		
		private System.Nullable<decimal> _cadera;
		
		private string _sexo;
		
		private System.Nullable<decimal> _altura;
		
		private System.Nullable<decimal> _cuello;
		
		private System.Nullable<decimal> _cintura;
		
		private System.Nullable<decimal> _indiceCintura_Altura;
		
		private System.Nullable<decimal> _masaCorporalMagra;
		
		private System.Nullable<decimal> _sobrepeso;
		
		private EntitySet<membresia_clientes> _membresia_clientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnpesoChanging(System.Nullable<decimal> value);
    partial void OnpesoChanged();
    partial void OncaderaChanging(System.Nullable<decimal> value);
    partial void OncaderaChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnalturaChanging(System.Nullable<decimal> value);
    partial void OnalturaChanged();
    partial void OncuelloChanging(System.Nullable<decimal> value);
    partial void OncuelloChanged();
    partial void OncinturaChanging(System.Nullable<decimal> value);
    partial void OncinturaChanged();
    partial void OnindiceCintura_AlturaChanging(System.Nullable<decimal> value);
    partial void OnindiceCintura_AlturaChanged();
    partial void OnmasaCorporalMagraChanging(System.Nullable<decimal> value);
    partial void OnmasaCorporalMagraChanged();
    partial void OnsobrepesoChanging(System.Nullable<decimal> value);
    partial void OnsobrepesoChanged();
    #endregion
		
		public clientes()
		{
			this._membresia_clientes = new EntitySet<membresia_clientes>(new Action<membresia_clientes>(this.attach_membresia_clientes), new Action<membresia_clientes>(this.detach_membresia_clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(50)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cadera", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cadera
		{
			get
			{
				return this._cadera;
			}
			set
			{
				if ((this._cadera != value))
				{
					this.OncaderaChanging(value);
					this.SendPropertyChanging();
					this._cadera = value;
					this.SendPropertyChanged("cadera");
					this.OncaderaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(50)")]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_altura", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> altura
		{
			get
			{
				return this._altura;
			}
			set
			{
				if ((this._altura != value))
				{
					this.OnalturaChanging(value);
					this.SendPropertyChanging();
					this._altura = value;
					this.SendPropertyChanged("altura");
					this.OnalturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuello", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cuello
		{
			get
			{
				return this._cuello;
			}
			set
			{
				if ((this._cuello != value))
				{
					this.OncuelloChanging(value);
					this.SendPropertyChanging();
					this._cuello = value;
					this.SendPropertyChanged("cuello");
					this.OncuelloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cintura", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cintura
		{
			get
			{
				return this._cintura;
			}
			set
			{
				if ((this._cintura != value))
				{
					this.OncinturaChanging(value);
					this.SendPropertyChanging();
					this._cintura = value;
					this.SendPropertyChanged("cintura");
					this.OncinturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indiceCintura_Altura", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> indiceCintura_Altura
		{
			get
			{
				return this._indiceCintura_Altura;
			}
			set
			{
				if ((this._indiceCintura_Altura != value))
				{
					this.OnindiceCintura_AlturaChanging(value);
					this.SendPropertyChanging();
					this._indiceCintura_Altura = value;
					this.SendPropertyChanged("indiceCintura_Altura");
					this.OnindiceCintura_AlturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masaCorporalMagra", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> masaCorporalMagra
		{
			get
			{
				return this._masaCorporalMagra;
			}
			set
			{
				if ((this._masaCorporalMagra != value))
				{
					this.OnmasaCorporalMagraChanging(value);
					this.SendPropertyChanging();
					this._masaCorporalMagra = value;
					this.SendPropertyChanged("masaCorporalMagra");
					this.OnmasaCorporalMagraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sobrepeso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sobrepeso
		{
			get
			{
				return this._sobrepeso;
			}
			set
			{
				if ((this._sobrepeso != value))
				{
					this.OnsobrepesoChanging(value);
					this.SendPropertyChanging();
					this._sobrepeso = value;
					this.SendPropertyChanged("sobrepeso");
					this.OnsobrepesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="clientes_membresia_clientes", Storage="_membresia_clientes", ThisKey="cedula", OtherKey="cedula_Cliente")]
		public EntitySet<membresia_clientes> membresia_clientes
		{
			get
			{
				return this._membresia_clientes;
			}
			set
			{
				this._membresia_clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_membresia_clientes(membresia_clientes entity)
		{
			this.SendPropertyChanging();
			entity.clientes = this;
		}
		
		private void detach_membresia_clientes(membresia_clientes entity)
		{
			this.SendPropertyChanging();
			entity.clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compra_producto")]
	public partial class compra_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_compra;
		
		private string _RUC_proveedor;
		
		private System.Nullable<System.DateTime> _fecha_compra;
		
		private string _tipo_documento;
		
		private string _num_documento;
		
		private string _id_empleado;
		
		private EntitySet<detalle_compra_producto> _detalle_compra_producto;
		
		private EntityRef<proveedores> _proveedores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_compraChanging(string value);
    partial void Onid_compraChanged();
    partial void OnRUC_proveedorChanging(string value);
    partial void OnRUC_proveedorChanged();
    partial void Onfecha_compraChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_compraChanged();
    partial void Ontipo_documentoChanging(string value);
    partial void Ontipo_documentoChanged();
    partial void Onnum_documentoChanging(string value);
    partial void Onnum_documentoChanged();
    partial void Onid_empleadoChanging(string value);
    partial void Onid_empleadoChanged();
    #endregion
		
		public compra_producto()
		{
			this._detalle_compra_producto = new EntitySet<detalle_compra_producto>(new Action<detalle_compra_producto>(this.attach_detalle_compra_producto), new Action<detalle_compra_producto>(this.detach_detalle_compra_producto));
			this._proveedores = default(EntityRef<proveedores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC_proveedor", DbType="VarChar(50)")]
		public string RUC_proveedor
		{
			get
			{
				return this._RUC_proveedor;
			}
			set
			{
				if ((this._RUC_proveedor != value))
				{
					if (this._proveedores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRUC_proveedorChanging(value);
					this.SendPropertyChanging();
					this._RUC_proveedor = value;
					this.SendPropertyChanged("RUC_proveedor");
					this.OnRUC_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_compra", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_compra
		{
			get
			{
				return this._fecha_compra;
			}
			set
			{
				if ((this._fecha_compra != value))
				{
					this.Onfecha_compraChanging(value);
					this.SendPropertyChanging();
					this._fecha_compra = value;
					this.SendPropertyChanged("fecha_compra");
					this.Onfecha_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_documento", DbType="VarChar(50)")]
		public string tipo_documento
		{
			get
			{
				return this._tipo_documento;
			}
			set
			{
				if ((this._tipo_documento != value))
				{
					this.Ontipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._tipo_documento = value;
					this.SendPropertyChanged("tipo_documento");
					this.Ontipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_documento", DbType="VarChar(50)")]
		public string num_documento
		{
			get
			{
				return this._num_documento;
			}
			set
			{
				if ((this._num_documento != value))
				{
					this.Onnum_documentoChanging(value);
					this.SendPropertyChanging();
					this._num_documento = value;
					this.SendPropertyChanged("num_documento");
					this.Onnum_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="VarChar(50)")]
		public string id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compra_producto_detalle_compra_producto", Storage="_detalle_compra_producto", ThisKey="id_compra", OtherKey="id_compra")]
		public EntitySet<detalle_compra_producto> detalle_compra_producto
		{
			get
			{
				return this._detalle_compra_producto;
			}
			set
			{
				this._detalle_compra_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_compra_producto", Storage="_proveedores", ThisKey="RUC_proveedor", OtherKey="RUC", IsForeignKey=true)]
		public proveedores proveedores
		{
			get
			{
				return this._proveedores.Entity;
			}
			set
			{
				proveedores previousValue = this._proveedores.Entity;
				if (((previousValue != value) 
							|| (this._proveedores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._proveedores.Entity = null;
						previousValue.compra_producto.Remove(this);
					}
					this._proveedores.Entity = value;
					if ((value != null))
					{
						value.compra_producto.Add(this);
						this._RUC_proveedor = value.RUC;
					}
					else
					{
						this._RUC_proveedor = default(string);
					}
					this.SendPropertyChanged("proveedores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_compra_producto(detalle_compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.compra_producto = this;
		}
		
		private void detach_detalle_compra_producto(detalle_compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.compra_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_compra_producto")]
	public partial class detalle_compra_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_detalle_compra;
		
		private string _id_compra;
		
		private string _id_producto;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<decimal> _precio_unitario;
		
		private EntityRef<compra_producto> _compra_producto;
		
		private EntityRef<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalle_compraChanging(string value);
    partial void Onid_detalle_compraChanged();
    partial void Onid_compraChanging(string value);
    partial void Onid_compraChanged();
    partial void Onid_productoChanging(string value);
    partial void Onid_productoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void Onprecio_unitarioChanging(System.Nullable<decimal> value);
    partial void Onprecio_unitarioChanged();
    #endregion
		
		public detalle_compra_producto()
		{
			this._compra_producto = default(EntityRef<compra_producto>);
			this._producto = default(EntityRef<producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle_compra", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_detalle_compra
		{
			get
			{
				return this._id_detalle_compra;
			}
			set
			{
				if ((this._id_detalle_compra != value))
				{
					this.Onid_detalle_compraChanging(value);
					this.SendPropertyChanging();
					this._id_detalle_compra = value;
					this.SendPropertyChanged("id_detalle_compra");
					this.Onid_detalle_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="VarChar(50)")]
		public string id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					if (this._compra_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="VarChar(50)")]
		public string id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unitario", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_unitario
		{
			get
			{
				return this._precio_unitario;
			}
			set
			{
				if ((this._precio_unitario != value))
				{
					this.Onprecio_unitarioChanging(value);
					this.SendPropertyChanging();
					this._precio_unitario = value;
					this.SendPropertyChanged("precio_unitario");
					this.Onprecio_unitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compra_producto_detalle_compra_producto", Storage="_compra_producto", ThisKey="id_compra", OtherKey="id_compra", IsForeignKey=true)]
		public compra_producto compra_producto
		{
			get
			{
				return this._compra_producto.Entity;
			}
			set
			{
				compra_producto previousValue = this._compra_producto.Entity;
				if (((previousValue != value) 
							|| (this._compra_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._compra_producto.Entity = null;
						previousValue.detalle_compra_producto.Remove(this);
					}
					this._compra_producto.Entity = value;
					if ((value != null))
					{
						value.detalle_compra_producto.Add(this);
						this._id_compra = value.id_compra;
					}
					else
					{
						this._id_compra = default(string);
					}
					this.SendPropertyChanged("compra_producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_detalle_compra_producto", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.detalle_compra_producto.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.detalle_compra_producto.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(string);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_venta_producto")]
	public partial class detalle_venta_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_detalle;
		
		private string _id_venta;
		
		private string _id_producto;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<decimal> _precio_unitario;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<venta_producto> _venta_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalleChanging(string value);
    partial void Onid_detalleChanged();
    partial void Onid_ventaChanging(string value);
    partial void Onid_ventaChanged();
    partial void Onid_productoChanging(string value);
    partial void Onid_productoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void Onprecio_unitarioChanging(System.Nullable<decimal> value);
    partial void Onprecio_unitarioChanged();
    #endregion
		
		public detalle_venta_producto()
		{
			this._producto = default(EntityRef<producto>);
			this._venta_producto = default(EntityRef<venta_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_detalle
		{
			get
			{
				return this._id_detalle;
			}
			set
			{
				if ((this._id_detalle != value))
				{
					this.Onid_detalleChanging(value);
					this.SendPropertyChanging();
					this._id_detalle = value;
					this.SendPropertyChanged("id_detalle");
					this.Onid_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="VarChar(50)")]
		public string id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					if (this._venta_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="VarChar(50)")]
		public string id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unitario", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_unitario
		{
			get
			{
				return this._precio_unitario;
			}
			set
			{
				if ((this._precio_unitario != value))
				{
					this.Onprecio_unitarioChanging(value);
					this.SendPropertyChanging();
					this._precio_unitario = value;
					this.SendPropertyChanged("precio_unitario");
					this.Onprecio_unitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_detalle_venta_producto", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.detalle_venta_producto.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.detalle_venta_producto.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(string);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venta_producto_detalle_venta_producto", Storage="_venta_producto", ThisKey="id_venta", OtherKey="id_venta", IsForeignKey=true)]
		public venta_producto venta_producto
		{
			get
			{
				return this._venta_producto.Entity;
			}
			set
			{
				venta_producto previousValue = this._venta_producto.Entity;
				if (((previousValue != value) 
							|| (this._venta_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._venta_producto.Entity = null;
						previousValue.detalle_venta_producto.Remove(this);
					}
					this._venta_producto.Entity = value;
					if ((value != null))
					{
						value.detalle_venta_producto.Add(this);
						this._id_venta = value.id_venta;
					}
					else
					{
						this._id_venta = default(string);
					}
					this.SendPropertyChanged("venta_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleados")]
	public partial class Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cedula_Empleado;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _login;
		
		private string _password;
		
		private string _tipo_acceso;
		
		private string _email;
		
		private EntitySet<faltas_Empleados> _faltas_Empleados;
		
		private EntitySet<pago_sueldo_Empleados> _pago_sueldo_Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncedula_EmpleadoChanging(string value);
    partial void Oncedula_EmpleadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Ontipo_accesoChanging(string value);
    partial void Ontipo_accesoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Empleados()
		{
			this._faltas_Empleados = new EntitySet<faltas_Empleados>(new Action<faltas_Empleados>(this.attach_faltas_Empleados), new Action<faltas_Empleados>(this.detach_faltas_Empleados));
			this._pago_sueldo_Empleados = new EntitySet<pago_sueldo_Empleados>(new Action<pago_sueldo_Empleados>(this.attach_pago_sueldo_Empleados), new Action<pago_sueldo_Empleados>(this.detach_pago_sueldo_Empleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_Empleado", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cedula_Empleado
		{
			get
			{
				return this._cedula_Empleado;
			}
			set
			{
				if ((this._cedula_Empleado != value))
				{
					this.Oncedula_EmpleadoChanging(value);
					this.SendPropertyChanging();
					this._cedula_Empleado = value;
					this.SendPropertyChanged("cedula_Empleado");
					this.Oncedula_EmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_acceso", DbType="VarChar(50)")]
		public string tipo_acceso
		{
			get
			{
				return this._tipo_acceso;
			}
			set
			{
				if ((this._tipo_acceso != value))
				{
					this.Ontipo_accesoChanging(value);
					this.SendPropertyChanging();
					this._tipo_acceso = value;
					this.SendPropertyChanged("tipo_acceso");
					this.Ontipo_accesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_faltas_Empleados", Storage="_faltas_Empleados", ThisKey="cedula_Empleado", OtherKey="cedula_Empleado")]
		public EntitySet<faltas_Empleados> faltas_Empleados
		{
			get
			{
				return this._faltas_Empleados;
			}
			set
			{
				this._faltas_Empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_pago_sueldo_Empleados", Storage="_pago_sueldo_Empleados", ThisKey="cedula_Empleado", OtherKey="cedula_empleado")]
		public EntitySet<pago_sueldo_Empleados> pago_sueldo_Empleados
		{
			get
			{
				return this._pago_sueldo_Empleados;
			}
			set
			{
				this._pago_sueldo_Empleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_faltas_Empleados(faltas_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = this;
		}
		
		private void detach_faltas_Empleados(faltas_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = null;
		}
		
		private void attach_pago_sueldo_Empleados(pago_sueldo_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = this;
		}
		
		private void detach_pago_sueldo_Empleados(pago_sueldo_Empleados entity)
		{
			this.SendPropertyChanging();
			entity.Empleados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.faltas_Empleados")]
	public partial class faltas_Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_falta;
		
		private string _cedula_Empleado;
		
		private System.Nullable<System.DateTime> _fecha_falta;
		
		private EntityRef<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_faltaChanging(string value);
    partial void OnId_faltaChanged();
    partial void Oncedula_EmpleadoChanging(string value);
    partial void Oncedula_EmpleadoChanged();
    partial void Onfecha_faltaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_faltaChanged();
    #endregion
		
		public faltas_Empleados()
		{
			this._Empleados = default(EntityRef<Empleados>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_falta", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_falta
		{
			get
			{
				return this._Id_falta;
			}
			set
			{
				if ((this._Id_falta != value))
				{
					this.OnId_faltaChanging(value);
					this.SendPropertyChanging();
					this._Id_falta = value;
					this.SendPropertyChanged("Id_falta");
					this.OnId_faltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_Empleado", DbType="VarChar(50)")]
		public string cedula_Empleado
		{
			get
			{
				return this._cedula_Empleado;
			}
			set
			{
				if ((this._cedula_Empleado != value))
				{
					if (this._Empleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncedula_EmpleadoChanging(value);
					this.SendPropertyChanging();
					this._cedula_Empleado = value;
					this.SendPropertyChanged("cedula_Empleado");
					this.Oncedula_EmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_falta", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_falta
		{
			get
			{
				return this._fecha_falta;
			}
			set
			{
				if ((this._fecha_falta != value))
				{
					this.Onfecha_faltaChanging(value);
					this.SendPropertyChanging();
					this._fecha_falta = value;
					this.SendPropertyChanged("fecha_falta");
					this.Onfecha_faltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_faltas_Empleados", Storage="_Empleados", ThisKey="cedula_Empleado", OtherKey="cedula_Empleado", IsForeignKey=true)]
		public Empleados Empleados
		{
			get
			{
				return this._Empleados.Entity;
			}
			set
			{
				Empleados previousValue = this._Empleados.Entity;
				if (((previousValue != value) 
							|| (this._Empleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleados.Entity = null;
						previousValue.faltas_Empleados.Remove(this);
					}
					this._Empleados.Entity = value;
					if ((value != null))
					{
						value.faltas_Empleados.Add(this);
						this._cedula_Empleado = value.cedula_Empleado;
					}
					else
					{
						this._cedula_Empleado = default(string);
					}
					this.SendPropertyChanged("Empleados");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.membresia_clientes")]
	public partial class membresia_clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_membresia;
		
		private string _cedula_Cliente;
		
		private System.Nullable<System.DateTime> _fecha_pago;
		
		private System.Nullable<System.DateTime> _fecha_proximo_pago;
		
		private string _nivel;
		
		private string _rutina;
		
		private EntityRef<clientes> _clientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_membresiaChanging(string value);
    partial void Onid_membresiaChanged();
    partial void Oncedula_ClienteChanging(string value);
    partial void Oncedula_ClienteChanged();
    partial void Onfecha_pagoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_pagoChanged();
    partial void Onfecha_proximo_pagoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_proximo_pagoChanged();
    partial void OnnivelChanging(string value);
    partial void OnnivelChanged();
    partial void OnrutinaChanging(string value);
    partial void OnrutinaChanged();
    #endregion
		
		public membresia_clientes()
		{
			this._clientes = default(EntityRef<clientes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_membresia", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_membresia
		{
			get
			{
				return this._id_membresia;
			}
			set
			{
				if ((this._id_membresia != value))
				{
					this.Onid_membresiaChanging(value);
					this.SendPropertyChanging();
					this._id_membresia = value;
					this.SendPropertyChanged("id_membresia");
					this.Onid_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_Cliente", DbType="VarChar(50)")]
		public string cedula_Cliente
		{
			get
			{
				return this._cedula_Cliente;
			}
			set
			{
				if ((this._cedula_Cliente != value))
				{
					if (this._clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncedula_ClienteChanging(value);
					this.SendPropertyChanging();
					this._cedula_Cliente = value;
					this.SendPropertyChanged("cedula_Cliente");
					this.Oncedula_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_pago", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_pago
		{
			get
			{
				return this._fecha_pago;
			}
			set
			{
				if ((this._fecha_pago != value))
				{
					this.Onfecha_pagoChanging(value);
					this.SendPropertyChanging();
					this._fecha_pago = value;
					this.SendPropertyChanged("fecha_pago");
					this.Onfecha_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_proximo_pago", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_proximo_pago
		{
			get
			{
				return this._fecha_proximo_pago;
			}
			set
			{
				if ((this._fecha_proximo_pago != value))
				{
					this.Onfecha_proximo_pagoChanging(value);
					this.SendPropertyChanging();
					this._fecha_proximo_pago = value;
					this.SendPropertyChanged("fecha_proximo_pago");
					this.Onfecha_proximo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(50)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this.OnnivelChanging(value);
					this.SendPropertyChanging();
					this._nivel = value;
					this.SendPropertyChanged("nivel");
					this.OnnivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rutina", DbType="VarChar(50)")]
		public string rutina
		{
			get
			{
				return this._rutina;
			}
			set
			{
				if ((this._rutina != value))
				{
					this.OnrutinaChanging(value);
					this.SendPropertyChanging();
					this._rutina = value;
					this.SendPropertyChanged("rutina");
					this.OnrutinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="clientes_membresia_clientes", Storage="_clientes", ThisKey="cedula_Cliente", OtherKey="cedula", IsForeignKey=true)]
		public clientes clientes
		{
			get
			{
				return this._clientes.Entity;
			}
			set
			{
				clientes previousValue = this._clientes.Entity;
				if (((previousValue != value) 
							|| (this._clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._clientes.Entity = null;
						previousValue.membresia_clientes.Remove(this);
					}
					this._clientes.Entity = value;
					if ((value != null))
					{
						value.membresia_clientes.Add(this);
						this._cedula_Cliente = value.cedula;
					}
					else
					{
						this._cedula_Cliente = default(string);
					}
					this.SendPropertyChanged("clientes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pago_sueldo_Empleados")]
	public partial class pago_sueldo_Empleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_pagoSueldo;
		
		private string _cedula_empleado;
		
		private string _Nro_CuentaBanco;
		
		private System.Nullable<decimal> _Monto_Pago;
		
		private System.Nullable<System.DateTime> _Fecha_Pago;
		
		private EntityRef<Empleados> _Empleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_pagoSueldoChanging(string value);
    partial void OnID_pagoSueldoChanged();
    partial void Oncedula_empleadoChanging(string value);
    partial void Oncedula_empleadoChanged();
    partial void OnNro_CuentaBancoChanging(string value);
    partial void OnNro_CuentaBancoChanged();
    partial void OnMonto_PagoChanging(System.Nullable<decimal> value);
    partial void OnMonto_PagoChanged();
    partial void OnFecha_PagoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_PagoChanged();
    #endregion
		
		public pago_sueldo_Empleados()
		{
			this._Empleados = default(EntityRef<Empleados>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_pagoSueldo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_pagoSueldo
		{
			get
			{
				return this._ID_pagoSueldo;
			}
			set
			{
				if ((this._ID_pagoSueldo != value))
				{
					this.OnID_pagoSueldoChanging(value);
					this.SendPropertyChanging();
					this._ID_pagoSueldo = value;
					this.SendPropertyChanged("ID_pagoSueldo");
					this.OnID_pagoSueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_empleado", DbType="VarChar(50)")]
		public string cedula_empleado
		{
			get
			{
				return this._cedula_empleado;
			}
			set
			{
				if ((this._cedula_empleado != value))
				{
					if (this._Empleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncedula_empleadoChanging(value);
					this.SendPropertyChanging();
					this._cedula_empleado = value;
					this.SendPropertyChanged("cedula_empleado");
					this.Oncedula_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nro_CuentaBanco", DbType="VarChar(50)")]
		public string Nro_CuentaBanco
		{
			get
			{
				return this._Nro_CuentaBanco;
			}
			set
			{
				if ((this._Nro_CuentaBanco != value))
				{
					this.OnNro_CuentaBancoChanging(value);
					this.SendPropertyChanging();
					this._Nro_CuentaBanco = value;
					this.SendPropertyChanged("Nro_CuentaBanco");
					this.OnNro_CuentaBancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto_Pago", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Monto_Pago
		{
			get
			{
				return this._Monto_Pago;
			}
			set
			{
				if ((this._Monto_Pago != value))
				{
					this.OnMonto_PagoChanging(value);
					this.SendPropertyChanging();
					this._Monto_Pago = value;
					this.SendPropertyChanged("Monto_Pago");
					this.OnMonto_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Pago", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Pago
		{
			get
			{
				return this._Fecha_Pago;
			}
			set
			{
				if ((this._Fecha_Pago != value))
				{
					this.OnFecha_PagoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Pago = value;
					this.SendPropertyChanged("Fecha_Pago");
					this.OnFecha_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleados_pago_sueldo_Empleados", Storage="_Empleados", ThisKey="cedula_empleado", OtherKey="cedula_Empleado", IsForeignKey=true)]
		public Empleados Empleados
		{
			get
			{
				return this._Empleados.Entity;
			}
			set
			{
				Empleados previousValue = this._Empleados.Entity;
				if (((previousValue != value) 
							|| (this._Empleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleados.Entity = null;
						previousValue.pago_sueldo_Empleados.Remove(this);
					}
					this._Empleados.Entity = value;
					if ((value != null))
					{
						value.pago_sueldo_Empleados.Add(this);
						this._cedula_empleado = value.cedula_Empleado;
					}
					else
					{
						this._cedula_empleado = default(string);
					}
					this.SendPropertyChanged("Empleados");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pagos_cliente")]
	public partial class pagos_cliente
	{
		
		private string _cedula_cliente;
		
		private string _id_membresia;
		
		private System.Nullable<decimal> _costo;
		
		private System.Nullable<decimal> _total;
		
		public pagos_cliente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="VarChar(50)")]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					this._cedula_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_membresia", DbType="VarChar(50)")]
		public string id_membresia
		{
			get
			{
				return this._id_membresia;
			}
			set
			{
				if ((this._id_membresia != value))
				{
					this._id_membresia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_producto;
		
		private string _id_categoria;
		
		private string _nombre_producto;
		
		private string _descripcion_producto;
		
		private System.Nullable<int> _stock_producto;
		
		private System.Nullable<decimal> _precio_compra_produc;
		
		private System.Nullable<decimal> _precio_venta_produc;
		
		private System.Nullable<System.DateTime> _fecha_vencimiento_prod;
		
		private System.Data.Linq.Binary _imagen_producto;
		
		private EntitySet<detalle_compra_producto> _detalle_compra_producto;
		
		private EntitySet<detalle_venta_producto> _detalle_venta_producto;
		
		private EntityRef<categoria> _categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(string value);
    partial void Onid_productoChanged();
    partial void Onid_categoriaChanging(string value);
    partial void Onid_categoriaChanged();
    partial void Onnombre_productoChanging(string value);
    partial void Onnombre_productoChanged();
    partial void Ondescripcion_productoChanging(string value);
    partial void Ondescripcion_productoChanged();
    partial void Onstock_productoChanging(System.Nullable<int> value);
    partial void Onstock_productoChanged();
    partial void Onprecio_compra_producChanging(System.Nullable<decimal> value);
    partial void Onprecio_compra_producChanged();
    partial void Onprecio_venta_producChanging(System.Nullable<decimal> value);
    partial void Onprecio_venta_producChanged();
    partial void Onfecha_vencimiento_prodChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_vencimiento_prodChanged();
    partial void Onimagen_productoChanging(System.Data.Linq.Binary value);
    partial void Onimagen_productoChanged();
    #endregion
		
		public producto()
		{
			this._detalle_compra_producto = new EntitySet<detalle_compra_producto>(new Action<detalle_compra_producto>(this.attach_detalle_compra_producto), new Action<detalle_compra_producto>(this.detach_detalle_compra_producto));
			this._detalle_venta_producto = new EntitySet<detalle_venta_producto>(new Action<detalle_venta_producto>(this.attach_detalle_venta_producto), new Action<detalle_venta_producto>(this.detach_detalle_venta_producto));
			this._categoria = default(EntityRef<categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="VarChar(50)")]
		public string id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_producto", DbType="VarChar(50)")]
		public string nombre_producto
		{
			get
			{
				return this._nombre_producto;
			}
			set
			{
				if ((this._nombre_producto != value))
				{
					this.Onnombre_productoChanging(value);
					this.SendPropertyChanging();
					this._nombre_producto = value;
					this.SendPropertyChanged("nombre_producto");
					this.Onnombre_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_producto", DbType="VarChar(50)")]
		public string descripcion_producto
		{
			get
			{
				return this._descripcion_producto;
			}
			set
			{
				if ((this._descripcion_producto != value))
				{
					this.Ondescripcion_productoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_producto = value;
					this.SendPropertyChanged("descripcion_producto");
					this.Ondescripcion_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_producto", DbType="Int")]
		public System.Nullable<int> stock_producto
		{
			get
			{
				return this._stock_producto;
			}
			set
			{
				if ((this._stock_producto != value))
				{
					this.Onstock_productoChanging(value);
					this.SendPropertyChanging();
					this._stock_producto = value;
					this.SendPropertyChanged("stock_producto");
					this.Onstock_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_compra_produc", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_compra_produc
		{
			get
			{
				return this._precio_compra_produc;
			}
			set
			{
				if ((this._precio_compra_produc != value))
				{
					this.Onprecio_compra_producChanging(value);
					this.SendPropertyChanging();
					this._precio_compra_produc = value;
					this.SendPropertyChanged("precio_compra_produc");
					this.Onprecio_compra_producChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta_produc", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> precio_venta_produc
		{
			get
			{
				return this._precio_venta_produc;
			}
			set
			{
				if ((this._precio_venta_produc != value))
				{
					this.Onprecio_venta_producChanging(value);
					this.SendPropertyChanging();
					this._precio_venta_produc = value;
					this.SendPropertyChanged("precio_venta_produc");
					this.Onprecio_venta_producChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_vencimiento_prod", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_vencimiento_prod
		{
			get
			{
				return this._fecha_vencimiento_prod;
			}
			set
			{
				if ((this._fecha_vencimiento_prod != value))
				{
					this.Onfecha_vencimiento_prodChanging(value);
					this.SendPropertyChanging();
					this._fecha_vencimiento_prod = value;
					this.SendPropertyChanged("fecha_vencimiento_prod");
					this.Onfecha_vencimiento_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen_producto", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagen_producto
		{
			get
			{
				return this._imagen_producto;
			}
			set
			{
				if ((this._imagen_producto != value))
				{
					this.Onimagen_productoChanging(value);
					this.SendPropertyChanging();
					this._imagen_producto = value;
					this.SendPropertyChanged("imagen_producto");
					this.Onimagen_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_detalle_compra_producto", Storage="_detalle_compra_producto", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<detalle_compra_producto> detalle_compra_producto
		{
			get
			{
				return this._detalle_compra_producto;
			}
			set
			{
				this._detalle_compra_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_detalle_venta_producto", Storage="_detalle_venta_producto", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<detalle_venta_producto> detalle_venta_producto
		{
			get
			{
				return this._detalle_venta_producto;
			}
			set
			{
				this._detalle_venta_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.producto.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.producto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(string);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_compra_producto(detalle_compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_detalle_compra_producto(detalle_compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
		
		private void attach_detalle_venta_producto(detalle_venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_detalle_venta_producto(detalle_venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.proveedores")]
	public partial class proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RUC;
		
		private string _nombre_proveedor;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _email;
		
		private EntitySet<compra_producto> _compra_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRUCChanging(string value);
    partial void OnRUCChanged();
    partial void Onnombre_proveedorChanging(string value);
    partial void Onnombre_proveedorChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public proveedores()
		{
			this._compra_producto = new EntitySet<compra_producto>(new Action<compra_producto>(this.attach_compra_producto), new Action<compra_producto>(this.detach_compra_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RUC
		{
			get
			{
				return this._RUC;
			}
			set
			{
				if ((this._RUC != value))
				{
					this.OnRUCChanging(value);
					this.SendPropertyChanging();
					this._RUC = value;
					this.SendPropertyChanged("RUC");
					this.OnRUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_proveedor", DbType="VarChar(50)")]
		public string nombre_proveedor
		{
			get
			{
				return this._nombre_proveedor;
			}
			set
			{
				if ((this._nombre_proveedor != value))
				{
					this.Onnombre_proveedorChanging(value);
					this.SendPropertyChanging();
					this._nombre_proveedor = value;
					this.SendPropertyChanged("nombre_proveedor");
					this.Onnombre_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="proveedores_compra_producto", Storage="_compra_producto", ThisKey="RUC", OtherKey="RUC_proveedor")]
		public EntitySet<compra_producto> compra_producto
		{
			get
			{
				return this._compra_producto;
			}
			set
			{
				this._compra_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_compra_producto(compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.proveedores = this;
		}
		
		private void detach_compra_producto(compra_producto entity)
		{
			this.SendPropertyChanging();
			entity.proveedores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.venta_producto")]
	public partial class venta_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_venta;
		
		private string _cedula_cliente;
		
		private System.Nullable<System.DateTime> _fecha_venta;
		
		private string _tipo_documento;
		
		private string _num_documento;
		
		private string _id_empleado;
		
		private EntitySet<detalle_venta_producto> _detalle_venta_producto;
		
		private EntityRef<cliente_venta_produc> _cliente_venta_produc;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ventaChanging(string value);
    partial void Onid_ventaChanged();
    partial void Oncedula_clienteChanging(string value);
    partial void Oncedula_clienteChanged();
    partial void Onfecha_ventaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ventaChanged();
    partial void Ontipo_documentoChanging(string value);
    partial void Ontipo_documentoChanged();
    partial void Onnum_documentoChanging(string value);
    partial void Onnum_documentoChanged();
    partial void Onid_empleadoChanging(string value);
    partial void Onid_empleadoChanged();
    #endregion
		
		public venta_producto()
		{
			this._detalle_venta_producto = new EntitySet<detalle_venta_producto>(new Action<detalle_venta_producto>(this.attach_detalle_venta_producto), new Action<detalle_venta_producto>(this.detach_detalle_venta_producto));
			this._cliente_venta_produc = default(EntityRef<cliente_venta_produc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_cliente", DbType="VarChar(50)")]
		public string cedula_cliente
		{
			get
			{
				return this._cedula_cliente;
			}
			set
			{
				if ((this._cedula_cliente != value))
				{
					if (this._cliente_venta_produc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncedula_clienteChanging(value);
					this.SendPropertyChanging();
					this._cedula_cliente = value;
					this.SendPropertyChanged("cedula_cliente");
					this.Oncedula_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_venta", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_venta
		{
			get
			{
				return this._fecha_venta;
			}
			set
			{
				if ((this._fecha_venta != value))
				{
					this.Onfecha_ventaChanging(value);
					this.SendPropertyChanging();
					this._fecha_venta = value;
					this.SendPropertyChanged("fecha_venta");
					this.Onfecha_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_documento", DbType="VarChar(50)")]
		public string tipo_documento
		{
			get
			{
				return this._tipo_documento;
			}
			set
			{
				if ((this._tipo_documento != value))
				{
					this.Ontipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._tipo_documento = value;
					this.SendPropertyChanged("tipo_documento");
					this.Ontipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_documento", DbType="VarChar(50)")]
		public string num_documento
		{
			get
			{
				return this._num_documento;
			}
			set
			{
				if ((this._num_documento != value))
				{
					this.Onnum_documentoChanging(value);
					this.SendPropertyChanging();
					this._num_documento = value;
					this.SendPropertyChanged("num_documento");
					this.Onnum_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="VarChar(50)")]
		public string id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venta_producto_detalle_venta_producto", Storage="_detalle_venta_producto", ThisKey="id_venta", OtherKey="id_venta")]
		public EntitySet<detalle_venta_producto> detalle_venta_producto
		{
			get
			{
				return this._detalle_venta_producto;
			}
			set
			{
				this._detalle_venta_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venta_produc_venta_producto", Storage="_cliente_venta_produc", ThisKey="cedula_cliente", OtherKey="cedula_cliente", IsForeignKey=true)]
		public cliente_venta_produc cliente_venta_produc
		{
			get
			{
				return this._cliente_venta_produc.Entity;
			}
			set
			{
				cliente_venta_produc previousValue = this._cliente_venta_produc.Entity;
				if (((previousValue != value) 
							|| (this._cliente_venta_produc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente_venta_produc.Entity = null;
						previousValue.venta_producto.Remove(this);
					}
					this._cliente_venta_produc.Entity = value;
					if ((value != null))
					{
						value.venta_producto.Add(this);
						this._cedula_cliente = value.cedula_cliente;
					}
					else
					{
						this._cedula_cliente = default(string);
					}
					this.SendPropertyChanged("cliente_venta_produc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_venta_producto(detalle_venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.venta_producto = this;
		}
		
		private void detach_detalle_venta_producto(detalle_venta_producto entity)
		{
			this.SendPropertyChanging();
			entity.venta_producto = null;
		}
	}
}
#pragma warning restore 1591
