<?xml version="1.0" encoding="utf-8"?><Database Name="proyecto" Class="bdDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=proyecto;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="systemaGYMFITNESS.Properties.Settings" SettingsPropertyName="proyectoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asistencia_Clientes" Member="Asistencia_Clientes">
    <Type Name="Asistencia_Clientes">
      <Column Name="cedula_cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="clientes_Asistencia_Clientes" Member="clientes" ThisKey="cedula_cliente" OtherKey="cedula" Type="clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.categoria" Member="categoria">
    <Type Name="categoria">
      <Column Name="id_categoria" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_categoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="categoria_producto" Member="producto" ThisKey="id_categoria" OtherKey="id_categoria" Type="producto" />
    </Type>
  </Table>
  <Table Name="dbo.cliente_venta_produc" Member="cliente_venta_produc">
    <Type Name="cliente_venta_produc">
      <Column Name="cedula_cliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="cliente_venta_produc_venta_producto" Member="venta_producto" ThisKey="cedula_cliente" OtherKey="cedula_cliente" Type="venta_producto" />
    </Type>
  </Table>
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="clientes">
      <Column Name="cedula" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellidos" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cadera" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="altura" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cuello" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cintura" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="indiceCintura_Altura" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="masaCorporalMagra" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="sobrepeso" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="clientes_Asistencia_Clientes" Member="Asistencia_Clientes" ThisKey="cedula" OtherKey="cedula_cliente" Type="Asistencia_Clientes" />
      <Association Name="clientes_membresia_clientes" Member="membresia_clientes" ThisKey="cedula" OtherKey="cedula_Cliente" Type="membresia_clientes" />
      <Association Name="clientes_pagos_cliente" Member="pagos_cliente" ThisKey="cedula" OtherKey="cedula_cliente" Type="pagos_cliente" />
    </Type>
  </Table>
  <Table Name="dbo.compra_producto" Member="compra_producto">
    <Type Name="compra_producto">
      <Column Name="id_compra" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RUC_proveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_compra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tipo_documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="num_documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_empleado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="compra_producto_detalle_compra_producto" Member="detalle_compra_producto" ThisKey="id_compra" OtherKey="id_compra" Type="detalle_compra_producto" />
      <Association Name="proveedores_compra_producto" Member="proveedores" ThisKey="RUC_proveedor" OtherKey="RUC" Type="proveedores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.detalle_compra_producto" Member="detalle_compra_producto">
    <Type Name="detalle_compra_producto">
      <Column Name="id_detalle_compra" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_compra" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_producto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio_unitario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="compra_producto_detalle_compra_producto" Member="compra_producto" ThisKey="id_compra" OtherKey="id_compra" Type="compra_producto" IsForeignKey="true" />
      <Association Name="producto_detalle_compra_producto" Member="producto" ThisKey="id_producto" OtherKey="id_producto" Type="producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.detalle_venta_producto" Member="detalle_venta_producto">
    <Type Name="detalle_venta_producto">
      <Column Name="id_detalle" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_venta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_producto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio_unitario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="producto_detalle_venta_producto" Member="producto" ThisKey="id_producto" OtherKey="id_producto" Type="producto" IsForeignKey="true" />
      <Association Name="venta_producto_detalle_venta_producto" Member="venta_producto" ThisKey="id_venta" OtherKey="id_venta" Type="venta_producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleados">
      <Column Name="cedula_Empleado" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipo_acceso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Empleados_faltas_Empleados" Member="faltas_Empleados" ThisKey="cedula_Empleado" OtherKey="cedula_Empleado" Type="faltas_Empleados" />
      <Association Name="Empleados_pago_sueldo_Empleados" Member="pago_sueldo_Empleados" ThisKey="cedula_Empleado" OtherKey="cedula_empleado" Type="pago_sueldo_Empleados" />
    </Type>
  </Table>
  <Table Name="dbo.faltas_Empleados" Member="faltas_Empleados">
    <Type Name="faltas_Empleados">
      <Column Name="Id_falta" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cedula_Empleado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_falta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Empleados_faltas_Empleados" Member="Empleados" ThisKey="cedula_Empleado" OtherKey="cedula_Empleado" Type="Empleados" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.membresia_clientes" Member="membresia_clientes">
    <Type Name="membresia_clientes">
      <Column Name="id_membresia" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cedula_Cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_pago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_proximo_pago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nivel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rutina" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="membresia_clientes_pagos_cliente" Member="pagos_cliente" ThisKey="id_membresia" OtherKey="id_membresia" Type="pagos_cliente" />
      <Association Name="clientes_membresia_clientes" Member="clientes" ThisKey="cedula_Cliente" OtherKey="cedula" Type="clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pago_sueldo_Empleados" Member="pago_sueldo_Empleados">
    <Type Name="pago_sueldo_Empleados">
      <Column Name="ID_pagoSueldo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cedula_empleado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nro_CuentaBanco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Monto_Pago" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Fecha_Pago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Empleados_pago_sueldo_Empleados" Member="Empleados" ThisKey="cedula_empleado" OtherKey="cedula_Empleado" Type="Empleados" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pagos_cliente" Member="pagos_cliente">
    <Type Name="pagos_cliente">
      <Column Name="cedula_cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_membresia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="costo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="clientes_pagos_cliente" Member="clientes" ThisKey="cedula_cliente" OtherKey="cedula" Type="clientes" IsForeignKey="true" />
      <Association Name="membresia_clientes_pagos_cliente" Member="membresia_clientes" ThisKey="id_membresia" OtherKey="id_membresia" Type="membresia_clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.producto" Member="producto">
    <Type Name="producto">
      <Column Name="id_producto" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_categoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nombre_producto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion_producto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="stock_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio_compra_produc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="precio_venta_produc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_vencimiento_prod" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="imagen_producto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="producto_detalle_compra_producto" Member="detalle_compra_producto" ThisKey="id_producto" OtherKey="id_producto" Type="detalle_compra_producto" />
      <Association Name="producto_detalle_venta_producto" Member="detalle_venta_producto" ThisKey="id_producto" OtherKey="id_producto" Type="detalle_venta_producto" />
      <Association Name="categoria_producto" Member="categoria" ThisKey="id_categoria" OtherKey="id_categoria" Type="categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.proveedores" Member="proveedores">
    <Type Name="proveedores">
      <Column Name="RUC" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_proveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="proveedores_compra_producto" Member="compra_producto" ThisKey="RUC" OtherKey="RUC_proveedor" Type="compra_producto" />
    </Type>
  </Table>
  <Table Name="dbo.venta_producto" Member="venta_producto">
    <Type Name="venta_producto">
      <Column Name="id_venta" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cedula_cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_venta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tipo_documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="num_documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_empleado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="venta_producto_detalle_venta_producto" Member="detalle_venta_producto" ThisKey="id_venta" OtherKey="id_venta" Type="detalle_venta_producto" />
      <Association Name="cliente_venta_produc_venta_producto" Member="cliente_venta_produc" ThisKey="cedula_cliente" OtherKey="cedula_cliente" Type="cliente_venta_produc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>